// Resolves the build version: explicit APP_VERSION env (used by Docker/CI),
// else `git describe` (tag, or commit hash with --always), else 'dev'.
// Writes frontend/src/generated/version.ts. Runs via prebuild/predev hooks.
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

function resolveVersion() {
  if (process.env.APP_VERSION) return process.env.APP_VERSION;
  try {
    const out = execSync('git describe --tags --always --dirty', {
      cwd: path.join(__dirname, '..', '..'),
      stdio: ['ignore', 'pipe', 'ignore'],
    });
    return out.toString().trim() || 'dev';
  } catch {
    return 'dev';
  }
}

const version = resolveVersion();
const dir = path.join(__dirname, '..', 'src', 'generated');
fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(
  path.join(dir, 'version.ts'),
  `// Auto-generated by scripts/gen-version.cjs — do not edit.\nexport const APP_VERSION = ${JSON.stringify(version)};\n`
);
console.log(`app version: ${version}`);
